import { Platform, StyleSheet } from "react-native";

export const demoStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#1a1a1a",
  },
  mainScroll: { flex: 1 },
  mainScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  header: {
    paddingBottom: 16,
    paddingHorizontal: 0,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingVertical: 4,
  },
  brandLogo: { width: 40, height: 40 },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#f8fafc",
    maxWidth: "100%",
  },
  titleSmall: { fontSize: 20 },
  subtitle: {
    fontSize: 14,
    color: "#9ca3af",
    textAlign: "center",
    marginTop: 6,
    maxWidth: "100%",
  },
  subtitleSmall: { fontSize: 12 },
  changeLink: {
    marginTop: 14,
    alignSelf: "center",
  },
  changeLinkText: {
    fontSize: 13,
    color: "#9ca3af",
  },
  modeSelectionContainer: {
    flex: 1,
    paddingTop: 12,
    paddingBottom: 16,
    gap: 14,
    maxWidth: "100%",
  },
  modeCard: {
    flex: 1,
    minHeight: 80,
    width: "100%",
    maxWidth: "100%",
    borderRadius: 20,
    backgroundColor: "#111827",
    borderWidth: 2,
    borderColor: "#374151",
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  modeCardInner: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
  },
  modeCardPrimary: {
    backgroundColor: "#1d283a",
    borderColor: "#3b82f6",
  },
  modeCardCta: {
    backgroundColor: "#111827",
    borderColor: "#3b82f6",
  },
  modeCardIcon: {
    fontSize: 40,
    marginBottom: 6,
    textAlign: "center",
  },
  modeLabel: {
    fontSize: 20,
    fontWeight: "700",
    color: "#f9fafb",
    marginBottom: 4,
    textAlign: "center",
    maxWidth: "100%",
  },
  modeLabelSmall: { fontSize: 16 },
  modeDescription: {
    fontSize: 14,
    color: "#9ca3af",
    textAlign: "center",
    paddingHorizontal: 6,
    maxWidth: "100%",
  },
  modeDescriptionSmall: { fontSize: 12, paddingHorizontal: 2 },
  justStart: {
    marginTop: 8,
    paddingVertical: 16,
    alignItems: "center",
  },
  justStartText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#93c5fd",
    textAlign: "center",
  },
  modeToggle: {
    flexDirection: "row",
    justifyContent: "center",
    paddingBottom: 8,
    gap: 8,
  },
  modeToggleChip: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#374151",
    backgroundColor: "#111827",
  },
  modeToggleChipActive: {
    borderColor: "#3b82f6",
    backgroundColor: "#1d283a",
  },
  modeToggleText: { fontSize: 13, color: "#9ca3af" },
  modeToggleTextActive: { color: "#e5e7eb", fontWeight: "600" },
  stage: { flex: 1 },
  search: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#374151",
    backgroundColor: "#020617",
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === "ios" ? 10 : 8,
    color: "#e5e7eb",
    fontSize: 14,
    marginBottom: 8,
  },
  pagerPage: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  figure: { flex: 1, width: "100%", overflow: "hidden" },
  figureFrame: {
    flex: 1,
    width: "100%",
    overflow: "hidden",
    paddingHorizontal: 46,
    paddingVertical: 8,
  },
  pagerChevron: {
    position: "absolute",
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(42,42,42,0.92)",
    borderWidth: 1,
    borderColor: "rgba(75,85,99,0.8)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    elevation: 4,
  },
  pagerChevronGlyph: {
    fontSize: 28,
    color: "#f8fafc",
    fontWeight: "300",
    marginTop: -2,
  },
  exerciseName: {
    fontSize: 22,
    fontWeight: "700",
    color: "#f8fafc",
    textAlign: "center",
  },
  exerciseFr: {
    fontSize: 13,
    color: "#9ca3af",
    textAlign: "center",
    marginTop: 2,
  },
  exerciseMeta: {
    fontSize: 12,
    color: "#9ca3af",
    textAlign: "center",
    marginTop: 2,
    textTransform: "capitalize",
  },
  empty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  emptyText: { fontSize: 15, color: "#9ca3af", textAlign: "center" },
  startButton: {
    marginTop: 16,
    borderRadius: 999,
    backgroundColor: "#3b82f6",
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  startButtonDisabled: { backgroundColor: "#1f2937" },
  startButtonText: { fontSize: 15, fontWeight: "600", color: "#f9fafb" },
  heightCard: { paddingTop: 8 },
  heightTitle: { fontSize: 15, fontWeight: "600", color: "#e5e7eb" },
  heightSubtitle: { fontSize: 12, color: "#9ca3af", marginTop: 2 },
  heightUnitRow: { marginTop: 12, gap: 8 },
  heightUnitChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#374151",
    backgroundColor: "#020617",
    marginRight: 8,
  },
  heightUnitChipActive: { borderColor: "#3b82f6", backgroundColor: "#1d283a" },
  heightUnitText: { fontSize: 13, color: "#9ca3af" },
  heightUnitTextActive: { color: "#e5e7eb", fontWeight: "600" },
  heightRow: { flexDirection: "row", alignItems: "center", marginTop: 12, gap: 12 },
  heightHalf: { flex: 1 },
  heightInput: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#374151",
    backgroundColor: "#020617",
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === "ios" ? 10 : 8,
    color: "#e5e7eb",
    fontSize: 14,
  },
  heightUnitLabel: { fontSize: 13, color: "#9ca3af" },
  trackingContainer: { flex: 1, backgroundColor: "#000" },
  webview: { flex: 1, backgroundColor: "#000" },
  overlay: { ...StyleSheet.absoluteFillObject },
  backButton: {
    position: "absolute",
    left: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(42,42,42,0.95)",
    borderWidth: 1,
    borderColor: "rgba(75,85,99,0.8)",
    alignItems: "center",
    justifyContent: "center",
  },
  backChevron: {
    fontSize: 28,
    color: "#f8fafc",
    fontWeight: "300",
    marginTop: -2,
  },
  readyPill: {
    position: "absolute",
    left: 68,
    height: 44,
    justifyContent: "center",
  },
  readyText: { fontSize: 13, color: "#e5e7eb", fontWeight: "500" },
  analysisLine: {
    position: "absolute",
    left: 16,
    right: 16,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "rgba(42,42,42,0.95)",
    borderWidth: 1,
    borderColor: "rgba(75,85,99,0.8)",
  },
  analysisText: { fontSize: 13, color: "#e5e7eb", textAlign: "center" },
  silhouette: {
    position: "absolute",
    left: "12%",
    right: "12%",
    top: "14%",
    bottom: "28%",
    opacity: 0.92,
  },
  bottomCards: {
    position: "absolute",
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  gradeCard: {
    minWidth: 80,
    maxWidth: "48%",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: "rgba(42,42,42,0.95)",
    borderWidth: 1,
    borderColor: "rgba(75,85,99,0.8)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  gradeLabel: {
    fontSize: 10,
    fontWeight: "600",
    color: "#9ca3af",
    letterSpacing: 1,
    marginBottom: 4,
  },
  gradeValue: { fontSize: 28, fontWeight: "700" },
  counterCard: {
    width: 110,
    height: 110,
    maxWidth: "48%",
    borderRadius: 12,
    backgroundColor: "rgba(42,42,42,0.95)",
    borderWidth: 1,
    borderColor: "rgba(75,85,99,0.8)",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    overflow: "hidden",
  },
  counterValue: { fontSize: 36, fontWeight: "700", color: "#f8fafc" },
  counterUnit: { fontSize: 12, color: "#9ca3af", marginTop: 4 },
  warmer: {
    position: "absolute",
    width: 1,
    height: 1,
    opacity: 0,
    overflow: "hidden",
  },
});
